### ISSUE TITLE
[BUG反馈]多标签页无法点击其它标签

### ISSUE THREAD

**Issue by qxchuckle** [buuing/mini-sandbox#10]
多标签页电脑端无法点击其它标签切换代码，手机端可正常点击切换。
文档例子和我自己网站内的都是这样。
https://buuing.github.io/mini-sandbox/#/docs/html
![image](https://user-images.githubusercontent.com/55614189/212624592-c4cfaa18-c288-4d56-8a9a-8d3808c3baea.png)
![image](https://user-images.githubusercontent.com/55614189/212625187-36c4856b-8d57-4181-88de-531d99c46ec5.png)

**Comment by buuing** [comment]
奇怪了, 我可以正常点击切换呀, 你是什么浏览器

**Comment by qxchuckle** [comment]
> 奇怪了，我可以正常点击切换呀，你是什么浏览器

火狐、谷歌、edge都是这样，电脑端

**Comment by qxchuckle** [comment]
> 奇怪了，我可以正常点击切换呀，你是什么浏览器

浏览器控制台也没有报错，css也没有禁止鼠标事件的代码，很奇怪，我录个屏

**Comment by buuing** [comment]
ldq404

**Comment by qxchuckle** [comment]
![1673856115(1)](https://user-images.githubusercontent.com/55614189/212626942-2a1c8bfc-f959-42c0-b792-bf1f4843331b.png)
有报错，

**Comment by qxchuckle** [comment]
![image](https://user-images.githubusercontent.com/55614189/212627126-93abb618-fcb9-42cc-8f8d-1963365e71b5.png)

**Comment by buuing** [comment]
加我微信, 我这里不能复现

**Comment by qxchuckle** [comment]
> 加我微信, 我这里不能复现
如何加您的微信，我的微信号qx1452798198

**Comment by buuing** [comment]
> ldq404

这不就是吗

**Comment by qxchuckle** [comment]
> > ldq404
> 
> 这不就是吗

已添加

**Comment by buuing** [comment]
最新版 `0.3.17` 已修复该问题

**Comment by buuing** [comment]
[【BUG】关于浏览器废弃 e.path 导致最新浏览器报错的解决方案](https://github.com/buuing/mini-sandbox/issues/11)
